# Generated by Django 3.2.16 on 2023-07-04 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumidor',
            fields=[
                ('id_consumidor', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=100, unique=True)),
                ('nome', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'consumidores_consumidor',
            },
        ),
    ]
